### ISSUE TITLE
AttachView at index 0?

### ISSUE THREAD

**Issue by antonshkurenko** [forceLain/AwesomeRecyclerView#1]
I'm trying to use your codebase to create my own custom layout manager (according to your [article](https://habrahabr.ru/company/eastbanctech/blog/267497/))

But I've found a bug:

Every time I wanted to scroll I've got this line executed (and edge effect appeared):

https://github.com/forceLain/AwesomeRecyclerView/blob/master/app/src/main/java/com/forcelain/android/awesomerecyclerview/view/AwesomeLayoutManager.java#L419

I debugged and found that problem was in re-attaching views. You used `addView(view, 0)` but attached to the bottom with [`attachView(view)`](https://github.com/forceLain/AwesomeRecyclerView/blob/master/app/src/main/java/com/forcelain/android/awesomerecyclerview/view/AwesomeLayoutManager.java#L183). That's why order of the views was wrong. 

Did this work well for you and something wrong with my code or this is a bug?

Because I changed code to the  `attachView(view, 0);` and now it works well.

P.S. My views aren't 75% of screen and have usual size (4-5 are at screen at the same time), maybe that revealed the problem?

**Comment by forceLain** [comment]
Yes, you are right, thanks.

**Comment by forceLain** [comment]
fixed in 71c4acec9d66a5cb917d83134e8207a26a5c4fc1
